---
title: "data analysis"
author: "grupo 5"
format: html
---

# Configuracion de mi entorno

```{r, echo=FALSE}
source("https://inkaverse.com/setup.r")
library(GerminaR)
library(dplyr)
```

# Importar datos
```{r, echo=FALSE}
url <- "https://docs.google.com/spreadsheets/d/1Eg67TqQINnAfa29ncqlPCAN7umUbyrkBbNOjd1us85Q/edit?gid=1454035531#gid=1454035531"

gs <- as_sheets_id(url)

fb <- range_read(gs
                 , sheet = "fb") %>% 
  mutate(across(factor1,  ~as.factor(.))) %>% 
  dplyr::select(!c(ger_7, ger_8, ger_9, ger_10)) %>% 
 as.data.frame()

str(fb)
```

# Indice de germinacion

```{r, echo=FALSE}
gsm <- ger_summary(SeedN = "seed"
                   , evalName = "ger_"
                   , data = fb
                   )
gsm %>% kable()

```

# Tiempo medio de germinacion 

```{r, echo=FALSE}
## Germination Percentage (GRP)

# analysis of variance

av <- aov(mgt ~ block + factor1, data = gsm)
anova(av)

library(cowplot)
mc_mgt <- ger_testcomp(aov = av
                       , comp = c("factor1")
                       , type = "snk")

mc_mgt$diagplot %>% 
  plot_grid(plotlist = ., ncol = 2, labels = "auto")

# mean comparison test

mc_mtg <- ger_testcomp(aov = av
                       , comp = c("factor1")
                       , type = "snk"
                       )

# data result

mc_grp$table %>% 
   kable(caption = "Mean germinacion time comparison")

# date result

plot <- mc_grp$table %>% 
   plot_smr (data = .
       , type = "bar"
       , x = "factor1"
       , y = "mgt"
       # , ylimits = c(0, 3, 0.5)
       , error = "ste"
       , sig = "sig"
       # , color = F
       )
plot
```

# Germinacion en el tiempo

```{r, echo=FALSE}
git <- ger_intime(Factor = "factor1"
                  , SeedN = "seed"
                  , evalName = "ger_"
                  , method = "percentage"
                  , data = fb
                  )

# data result

git %>% 
   head(10) %>% 
   kable(caption = "Cumulative germination by nacl factor")
# date result

plot1 <- git%>% 
   fplot(data = .
       , type = "line"
       , x = "evaluation"
       , y = "mean"
       , group = "factor1"
       , ylab = "Germination ('%')"
       , xlab = "Dias"
       # , ylimits = c(0, 3, 0.5)
       , error = "ste"
       , sig = "ste"
       , color = T
       # , color = F
       )

plot1

plot2<- git %>% 
   fplot(data = .
        , type = "line"
        , x = "evaluation"
        , y = "mean"
        , group = "factor1"
        , ylimits = c(0, 110, 10)
        , ylab = "Germination ('%')"
        , xlab = "Day"
        , color = T
        , error = "ste"
        )
plot2

```



